spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: postgres
    password: qwerty
    hikari:
      leakDetectionThreshold: 60000
      maximumPoolSize: 10
      minimumIdle: 1
      poolName: SpringBootJPAHikariCP