# @name create product
POST localhost:8080/product
Content-Type: application/json

{
  "name": "wwtte",
  "price": 12.00,
  "description": "eteawrt"
}

###
# @name get all products
GET 127.0.0.1:8080/product/

###
# @name update product
PUT localhost:8080/product/8133930b-6bca-49ff-a878-dd72f8d3a332
Content-Type: application/json

{
  "name": "wqrqw",
  "price": 213.24,
  "description": "qwe"
}

###
### Not implemented
POST http://localhost:8080/user/auth
Content-Type: application/json

{
  "login": "test",
  "password": "error"
}